# Generated by Django 6.0 on 2025-12-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('tank', 'Tank'), ('car', 'Car'), ('apc', 'APC'), ('ifv', 'IFV'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('damaged', 'Damaged'), ('destroyed', 'Destroyed'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('max_speed', models.PositiveIntegerField(blank=True, help_text='Max speed in km/h', null=True)),
                ('armor', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], help_text='armor classification', max_length=20)),
                ('armor_level', models.PositiveIntegerField(help_text='Abstract armor rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicles.vehicle')),
            ],
        ),
    ]
