# Generated by Django 6.0 on 2025-12-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='old_status',
            field=models.CharField(default='New', max_length=20, null=True),
        ),
    ]
