# Generated by Django 6.0 on 2026-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='event',
            field=models.TextField(blank=True, default='added', max_length=20),
            preserve_default=False,
        ),
    ]
